# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Update Atom Feed

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  schedule:
    # POSIX cron syntax:
    # https://pubs.opengroup.org/onlinepubs/9699919799/utilities/crontab.html#tag_20_25_07
    - cron: '0 0,12 * * *' # 매일 자정에 실행

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Generate feed.xml
      run: python src
    - name: Push to the output branch
      uses: crazy-max/ghaction-github-pages@v3.1.0
      with:
        target_branch: dist
        build_dir: docs
        keep_history: true
        author: Hepheir <19310326+Hepheir@users.noreply.github.com>
        commit_message: "docs(feed.xml): automatic update"
        allow_empty_commit: false
        verbose: true
        jekyll: false
      env:
        GITHUB_TOKEN: ${{ github.token }}
